name: CI

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Name of environment to deploy'
        required: true
        default: 'Staging'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  ENVIRONMENT: Develop

jobs:
  env:
    runs-on: ubuntu-latest
    outputs:
      ENVIRONMENT: ${{ steps.staging.outputs.ENVIRONMENT || steps.production.outputs.ENVIRONMENT || steps.testing.outputs.ENVIRONMENT || env.ENVIRONMENT  }}
    steps:
      - if: github.event.inputs.environment == 'Staging'
        id: staging
        run: echo "::set-output name=ENVIRONMENT::Staging"
      - if: github.event.inputs.environment == 'Production'
        id: production
        run: echo "::set-output name=ENVIRONMENT::Production"
      - if: github.event.inputs.environment == 'Testing'
        id: testing
        run: echo "::set-output name=ENVIRONMENT::Testing"
  build:
    needs:
      - env
    runs-on: ubuntu-latest
    environment:
      name: ${{ needs.env.outputs.ENVIRONMENT }}
    env:
      ENVIRONMENT: ${{ needs.env.outputs.ENVIRONMENT }}
      ENV_ONLY_SECRET: ${{ secrets.ENV_ONLY_SECRET }}
      REPO_ONLY_SECRET: ${{ secrets.REPO_ONLY_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: |
          echo Hello, world! from $ENVIRONMENT
          echo ENV_ONLY_SECRET $ENV_ONLY_SECRET
          echo REPO_ONLY_SECRET $REPO_ONLY_SECRET
